cgdd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponse # For the robots.txt response.

import gendep.views  # To call the awstats in views.py


urlpatterns = [
#    url(r'^(?:gendep|api)/', include('gendep.urls')), # This didn't work, (as genedp.utls contains app_name = 'gendep') but split the gendep urls in two files, but keep as one for simplicity for now.

    url(r'^admin/', admin.site.urls),
    url(r'^gendep/', include('gendep.urls')),
#    url(r'^api/', include('gendep.urls_api')),

    url(r'^stats/', admin.site.admin_view(gendep.views.awstats_view), name='stats'),     # The 'self.admin_site.admin_view()' wrapper checks that have admin permissions and marks the page as non-cacheable.
    # The above also for eg: stats/awstats?output=allhosts      # For the links within the awstats.pl (as set by the 'WrapperScript="stats"' in the awstats config file.

    # The 'robots.txt' response for web search engine robots (this empty 'Disallow:' means all pages are allowed)
    url(r'^robots.txt', lambda x: HttpResponse("User-Agent: *\nDisallow:", content_type="text/plain"), name="robots_file"),
    
    # To enable the domain name: "http://www.cancergd.org" to go to the gendep app, without needing /gendep/ suffix.
    # From: http://stackoverflow.com/questions/22468813/how-do-i-set-my-django-views-url-to-the-root-domain-of-my-website    
    # The following url should be the final url() here so that Django can test for matches to the above urls first.
    
    # Added 'namespace="rootgendep"' to fix the warning when runserver.bat. So the cancergd namespaces are: ['admin', 'gendep', 'rootgendep'].
    #    WARNINGS: ?: (urls.W005) URL namespace 'gendep' isn't unique. You may not be able to reverse all URLs in this namespace
    # The warning is generated by script: C:\Users\HP\AppData\Local\Programs\Python\Python35\Lib\site-packages\django\core\checks\urls.py      
    url(r'^', include('gendep.urls', namespace = "rootgendep")),
    #  Also see: https://docs.djangoproject.com/en/1.11/topics/http/urls/
    
    # url(r'^', include('gendep.urls')),
]

gendep/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page
#from django.views.decorators.csrf import csrf_protect
from django.contrib import admin # To add the admin wrapper to awstats_view

from . import views

app_name = 'gendep'

# Some info about url patterns: http://www.webforefront.com/django/accessurlparamsviewmethods.html
# Optional parameters: http://stackoverflow.com/questions/14351048/django-optional-url-parameters

cachetime = 60*60*24    # Cache time in seconds - so this view will be cached for 24 hours.
newscachetime = 10      # Cache time in seconds - so this view will be cached for 10 seconds.
#cachetime = 1

urlpatterns = [
    
    url(r'^$',          cache_page(cachetime)(views.index),    name='home'),
    url(r'^about/$',    cache_page(cachetime)(views.about),    name='about'),
    url(r'^news/$',     cache_page(newscachetime)(views.news), name='news'),
    url(r'^tutorial/$', cache_page(cachetime)(views.tutorial), name='tutorial'),    
    url(r'^drivers/$',  cache_page(cachetime)(views.drivers),  name='drivers'),    
    url(r'^targets/$',  cache_page(cachetime)(views.targets),  name='targets'),
    url(r'^tissues/$',  cache_page(cachetime)(views.tissues),  name='tissues'),
    url(r'^studies/$',  cache_page(cachetime)(views.studies),  name='studies'),    
    url(r'^faq/$',      cache_page(cachetime)(views.faq),      name='faq'),
    url(r'^download/$', cache_page(cachetime)(views.download), name='download'),
    url(r'^study/(?P<study_pmid>[0-9A-Za-z]+)/$', cache_page(cachetime)(views.show_study), name='show_study'), # pmid could be 'Pending0001'
        
    url(r'^contact/$', views.contact, name='contact'), # Don't cache this contact form, as uses a csrf_token, and need it protected, see: https://docs.djangoproject.com/en/1.10/ref/csrf/#caching  
    # Alternatively add the "csrf_protect" decorator, but doesn't seem to be permitted within this url() syntax:
    # url(r'^contact/$', cache_page(cachetime) csrf_protect() views.contact, name='contact'), # Don't cache this contact form, as uses a csrf_token, and need it protected, see: https://docs.djangoproject.com/en/1.10/ref/csrf/#caching  
    
    url(r'^contact/$', views.contact, name='contact'), # Don't cache this contact form, as uses a csrf_token, and need it protected, see: https://docs.djangoproject.com/en/1.10/ref/csrf/#caching  
    
    url(r'^log_comment/', views.log_comment, name='log_comment'),  # Don't cache this log_comment.

    url(r'^get_drivers/', views.get_drivers, name='get_drivers'),
        
    # url(r'^get_dependencies/(?P<search_by>(?:mysearchby|driver|target))/(?P<gene_name>[0-9A-Za-z\-_\.]+)/(?P<histotype_name>[0-9A-Za-z\_]+)/(?P<study_pmid>[0-9A-Za-z\_]+)/$', views.get_dependencies, name='get_dependencies'), 
    url(r'^get_dependencies/(?P<search_by>(?:mysearchby|driver|target))/(?P<entrez_id>[0-9a-z]+)/(?P<histotype_name>[0-9A-Za-z\_]+)/(?P<study_pmid>[0-9A-Za-z\_]+)/$', cache_page(cachetime)(views.get_dependencies), name='get_dependencies'),
    # '\_' is needed to match ALL_STUDIES and ALL_HISTOTYPES

    # url(r'^download_csv/(?P<delim_type>(?:csv|tsv|xlsx))/(?P<search_by>(?:mysearchby|driver|target))/(?P<gene_name>[0-9A-Za-z\-_\.]+)/(?P<histotype_name>[0-9A-Za-z\_]+)/(?P<study_pmid>[0-9A-Za-z\_]+)/$', views.download_dependencies_as_csv_file, name='download_csv'), # \_ needed to match ALL_STUDIES and ALL_HISTOTYPES
    url(r'^download_csv/(?P<delim_type>(?:csv|tsv|xlsx))/(?P<search_by>(?:mysearchby|driver|target))/(?P<entrez_id>[0-9a-z]+)/(?P<histotype_name>[0-9A-Za-z\_]+)/(?P<study_pmid>[0-9A-Za-z\_]+)/$', cache_page(cachetime)(views.download_dependencies_as_csv_file), name='download_csv'), # \_ needed to match ALL_STUDIES and ALL_HISTOTYPES

    url(r'get_boxplot/(?P<dataformat>(?:myformat|csvplot|jsonplot|jsonplotandgene|csv|download))/(?P<driver_name>[0-9A-Za-z\-_\.]+)/(?P<target_name>[0-9A-Za-z\-_\.]+)/(?P<histotype_name>[0-9A-Za-z\_]+)/(?P<study_pmid>[0-9A-Za-z\_]+)/$', cache_page(cachetime)(views.get_boxplot), name='get_boxplot'),
    # Still using target gene_name (as we don't pass the target entrez_id to the html dependency table as means entrez_id would need top be sent for each dependency table row)
    # Still using driver gene_name, as could have searched by target, so wouldn't have entrez_id for drivers in the html dependency table.
    
    url(r'^get_gene_info/(?P<gene_name>[0-9A-Za-z\-_\.]+)/$', cache_page(cachetime)(views.gene_info), name='get_gene_info'),

    # Allow carriage return character (as is %0D) - using a semicolon as the divider instead of return:
    url(r'get_stringdb_interactions/(?P<required_score>[0-9]+)/(?P<protein_list>[0-9A-Za-z\.;\%\r]+)/$', views.get_stringdb_interactions, name='get_stringdb_interactions'),
    
    # For sending protein_list request as HTML GET or better POST, as browsers have a max url length, especially IE, in address bar so use POST:
    url(r'get_stringdb_interactions/(?P<required_score>[0-9]+)/$', views.get_stringdb_interactions, name='get_stringdb_interactions_post'),
    
    url(r'cytoscape/(?P<required_score>[0-9]+)/(?P<protein_list>[0-9A-Za-z\.;\%\r]+)/(?P<gene_list>[0-9A-Za-z\-_\.;\%\r]+)/$', views.cytoscape, name='cytoscape_get'),
    
    # For sending protein_list and gene_list as HTML GET or POST:
    url(r'cytoscape/(?P<required_score>[0-9]+)/$', views.cytoscape, name='cytoscape_post'),
    
    url(r'^(?P<search_by>(?:mysearchby|driver|target))/(?P<gene_name>[0-9A-Za-z\-_\.]*)/(?P<histotype_name>[0-9A-Za-z\_]*)/(?P<study_pmid>[0-9A-Za-z\_]*)/$', views.index, name='home_search_by_gene_tissue_pmid'),
    # url(r'^(?P<search_by>(?:mysearchby|driver|target))/(?P<entrez_id>[0-9a-z]*)/(?P<histotype_name>[0-9A-Za-z\_]*)/(?P<study_pmid>[0-9A-Za-z\_]*)/$', views.index, name='home_search_by_gene_tissue_pmid'),    

    url(r'^(?P<search_by>(?:mysearchby|driver|target))/(?P<gene_name>[0-9A-Za-z\-_\.]+)/$', views.index, name='home_search_by_gene'),
    # url(r'^(?P<search_by>(?:mysearchby|driver|target))/(?P<entrez_id>[0-9a-z]+)/$', views.index, name='home_search_by_gene'),

    url(r'^(?P<search_by>(?:mysearchby|driver|target))/$', views.index, name='home_search_by'), # Needs to be at end as could otherwise interpret 'about' as driver name.
        
    # eg:  http://localhost:8000/gendep/driver/ERBB2/PANCAN/26947069/

    # url(r'^driver/(?P<driver>[0-9A-Za-z\-_\.]+)/$', views.index, name='driver'), # ie: /driver/gene_name/
    # The parameters could be optional, so use '*'. If "//" not permitted in url, then could use "ALL/ALL/" (or "ALL_GENES", "ALL_HISTOTYPES", "ALL_STUDIES")
    # http://stackoverflow.com/questions/2325433/making-a-regex-django-url-token-optional
    # Better: https://gist.github.com/c4urself/1028897
    #url(r'^(?P<search_by>(?:mysearchby|driver|target))/(?P<gene_name>[0-9A-Za-z\-_\.]+)/(?P<histotype_name>[0-9A-Za-z\_]+)/(?P<study_pmid>[0-9A-Za-z\_]+)$', views.index, name='home_search_by'), # Needs to be at end as could otherwise interpret 'about' as driver name.    
    
    
]

gendep/templates/gendep/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  {% load staticfiles %}
  {% block title %}<title>CancerGD.org: a database of Cancer Genetic Dependencies</title>{% endblock %}
  {% block links_top %}{% endblock %} {# Putting non-essential scripts at bottom can speedup display of webpage #}
  {# Need to call my style sheet after jQuery one, so that mine overwrites the jquery defaults #}
  <link rel="icon" type="image/png" href="{% static 'gendep/images/favicon-32x32.png' %}" sizes="32x32" />
  <link rel="icon" type="image/png" href="{% static 'gendep/images/favicon-16x16.png' %}" sizes="16x16" />  
  <link rel="stylesheet" type="text/css" href="{% static 'gendep/style.css' %}" />
  {% block scripts %}{% endblock %} 
</head>
<body>

<div id="header">
<table align="center" style="padding: 0;"><tr>
{% comment "Needs new logo, as named changed to CancerGD" %}
<td rowspan="2">
<img src="{% static 'gendep/images/CGDD_logo3_smallest.png' %}" alt="CancerGD.org" width="101" height="62"/>
</td>
{% endcomment %}
<td>
 &nbsp; &nbsp; <a href="{% url 'gendep:home' %}">Home/Search</a>
{% comment "Not using ByTarget search at present" %} 
 &nbsp; &nbsp; <a href="{% url 'gendep:home_search_by' search_by='target' %}">ByTarget</a>
{% endcomment %} 
 &nbsp; &nbsp; <a href="{% url 'gendep:about' %}">About</a>
 &nbsp; &nbsp; <a href="{% url 'gendep:news' %}">News</a>
 &nbsp; &nbsp; <a href="{% url 'gendep:tutorial' %}">Tutorial</a>
 &nbsp; &nbsp; <a href="{% url 'gendep:drivers' %}">Drivers</a>
{# &nbsp; &nbsp; <a href="{ % url 'gendep:targets' % }">Target genes</a> #}
{# &nbsp; &nbsp; <a href="{% url 'gendep:tissues' %}">Tissues</a> #}
 &nbsp; &nbsp; <a href="{% url 'gendep:studies' %}">Studies</a>
 &nbsp; &nbsp; <a href="{% url 'gendep:download' %}">Downloads</a>
 &nbsp; &nbsp; <a href="{% url 'gendep:faq' %}">FAQ</a>
 &nbsp; &nbsp; <a href="{% url 'gendep:contact' %}">Contact</a>
</td>
<tr><td> 
<h1>CancerGD.org: a database of Cancer Genetic Dependencies</h1>
</td></tr></table>
</div>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div id="maintext_div">
{% block content %}{% endblock %}
</div>
<div id="maintable_div" style="padding: 30 0">
{% block table %}{% endblock %}
</div>
<div id="footer">
<hr style="color: #aa66ff;" />
<table align="center" cellpadding="10"><tr>
<td><a href="http://www.ucd.ie/sbi/" title="Systems Biology Ireland"><img src="{% static 'gendep/images/SBI-logo-138w79h.png' %}" alt="Systems Biology Ireland" width="138" height="79" /></a></td>
<td><a href="http://www.ucd.ie/" title="University College Dublin"><img src="{% static 'gendep/images/UCD_maincore_logo.png' %}" alt="University College Dublin" width="276" height="69" /></a></td>
<td><a href="http://www.icr.ac.uk/" title="The Institute of Cancer Research"><img src="{% static 'gendep/images/ICR_logo_smaller.png' %}" alt="The Institute of Cancer Research" width="283" height="55" /></a></td>
<td><a href="http://www.hrb.ie/" title="The Health Research Board, Ireland"><img src="{% static 'gendep/images/HRB_logo_blue_thumb_200x80px.jpg' %}" alt="The Health Research Board, Ireland" width="200" height="80" /></a></td>
</tr></table>

</div>
{% block links_bottom %}{% endblock %}
</body>
</html>

gendep/templates/gendep/contact.html
{% extends 'gendep/base.html' %}
{% load staticfiles %}

{% block scripts %}
<script type="text/javascript">

function check_comment_form() {
  // As the autocomplete form permits text that doesn't match any driver:
  var name = document.getElementById("name").value;  
  var email = document.getElementById("email").value;
  var comment = document.getElementById("comment").value;
  var msg = '';  
  var elem = null;

  if (name == null || name.replace(/\s*/, '') == "") {
    msg += "'Your name' field needs a value entered";
	elem = document.getElementById("name");
    }
  if (email == null || email.replace(/\s*/, '') == "") {
    msg += "\n'Your email' field needs a value entered";
    if (elem==null) {elem = document.getElementById("email");}
    }
  if (comment == null || comment.replace(/\s*/, '') == "") {
    msg += "\n'Your comment' field needs a value entered";
	if (elem==null) {elem = document.getElementById("comment");}
    }
  
  if (msg !='') {
    alert(msg);
	// evt.preventDefault();
	if (elem!=null) {elem.focus();}
	return false;
	}	
  else {
    document.getElementById("comment_submit_button").value="Submitting...";
    return true;
  }
}

</script>
{% endblock %}

{% block content %}
<h1>Contact</h1>


<!-- Could add the mailgun email validator: https://github.com/mailgun/validator-demo -->

<p>We welcome your comments and queries:</p>
<table align="center">
<tr><td>
<form name="form" id="form" method="post" onsubmit="return check_comment_form();" action="{% url 'gendep:log_comment' %}">
{% csrf_token %}
<label for="name">Your name:</label><br/>
<input type="text" size="80" name="name" id="name" placeholder="Your name" required />
<br/> &nbsp; <br/>
<label for="email">Your email:</label><br/>
<input type="email" size="80" name="email" id="email" placeholder="Your email" required />
<br/> &nbsp; <br/>
{% comment%}
<label for="interest">Your area of interest:</label><br/>
<textarea rows="3" cols="81" name="interest" id="interest" placeholder="Your area of interest" required ></textarea>
<br/> &nbsp; <br/>
{% endcomment %}
<label for="comment">Your comment/query:</label><br/>
<textarea rows="10" cols="81" name="comment" id="comment" placeholder="Your comment or query" required ></textarea>
<br/> &nbsp; <br/>
{% comment %}
<!-- Can reenable this check if get spammed -->
<label for="human">To confirm that you aren't a web-spam-robot, please give answer as a figure, eg. 8:</label><br/>
five plus two is: <input type="text" size="10" name="human" id="human" placeholder="Your answer" required />
<br/> &nbsp; <br/>
{% endcomment %}
<input type="submit" id="comment_submit_button" value="Submit comment"/>
</form>
</td></tr>
</table>

<br/>
<p>Or email Colm Ryan (Systems Biology Ireland): <span style="color:blue;">cancergenetics [AT] ucd.ie</span></p>
{% endblock%}

gendep/templates/gendep/log_comment.html
{% extends 'gendep/base.html' %}
{% load staticfiles %}
{% block content %}
<h1>Thank you for your comment/query:</h1>
<p><b>Your name:</b> {{ name }}</p>
<p><b>Your email:</b> {{ email }}</p>
<p><b>Your comment/query:</b><br/> {{ comment|linebreaks }}</p>
<p><b>{{ email_sent }}</b></p>
{% endblock %}

gendep/templates/gendep/news.html
{% extends 'gendep/base.html' %}
{% load staticfiles %}
{% block links_top %}
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css" class="ui-theme" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
{% endblock %}

{% block scripts %}
<style type="text/css">
  .ui-tooltip {
    padding: 5px 5px;
    background: #ffffc0;
	/*color: white; */
    border-radius: 10px;	
	z-index: 2147478001;  /* So will appear above the fancybox 2147478000*/
    font: bold 12px "Helvetica Neue", Sans-Serif;
  }
</style>


<script type="text/javascript">

// Convert the histotypes to display names, eg:.
// In future could sort displaynames into alphabetic order, as not sorted by the SQLite database query (but should be by the MySQL query)
function histotypes_to_displaynames(histotype_list) {
  var displaynames = "";
  var histotypes = histotype_list.split(",");
  for (var i=0; i<histotypes.length; i++) {
    if (displaynames !== "") {displaynames += ", ";}
    switch (histotypes[i]) {
      case "": break;
      {% for histotype in histotype_list %}
      case "{{ histotype.0 }}": displaynames += "{{ histotype.1 }}"; break; {% endfor %}	
      // case "BONE": return "Osteosarcoma"; // added for the CVG boxplot legend.
      case "ALL_HISTOTYPES": displaynames += "All tissues"; break; // Not needed.
      default: displaynames+= 'Error: Histotype "'+histotypes[i]+'" Not Found';
    }
  }
  return displaynames;
}



  function add_tooltips_to_driver_table() {
	// Initialise the Tooltips
	$('#study_table_tbody').tooltip({
	  items: "[data-study], [data-authors], [data-experiment_type], [data-histotype_list]",
	  show: false, // effect
	  hide: false,
      track: true, // follow mouse
	  position: {
        my: "center+15% bottom-20",  // this center+10% should match the ".arrow.left {left: 40%;} in 'style.css' file
        at: "center top",
	    using: function( position, feedback ) {
          $( this ).css( position );
		  
		  $( "<div>" )
            .addClass( "arrow" )
            .addClass( feedback.vertical )
            .addClass( feedback.horizontal )
            .appendTo( this );
        }
	  },
	  
      content: function(callback) {  // 'callback' function is called below with the data:
        var element = $( this );
/*
        if ( element.is( "[data-study_list]" ) ) {
          var gene_name = element.attr("data-gene");  // was: = element.text();
		  if (gene_name in gene_info_cache) {
			var result = format_gene_info_for_tooltip(gene_info_cache[gene_name]);
			callback(result);
			}
		  else {
            var url = global_url_gene_info_for_mygene.replace('mygene',gene_name);
            $.ajax({
              url: url,
              dataType: 'json', 
            })
            .done(function(data, textStatus, jqXHR) {  // or use .always(...)
              if (data['success']) {
			  	gene_info_cache[gene_name] = data; // cache to retrieve faster next time.
			    result = format_gene_info_for_tooltip(data);
			    callback(result);
				}
			  else {callback("Error: "+data['message'])}
		    })
		    .fail(function(jqXHR, textStatus, errorThrown) {
			  callback("Ajax Failed: '"+textStatus+"'  '"+errorThrown+"'");
            })
		  }
        }
*/        
 
        if ( element.is( "[data-study]" ) ) {
          return element.attr("data-study");
        }
        if ( element.is( "[data-authors]" ) ) {
          return element.attr("data-authors");
        }				
        else if ( element.is( "[data-experiment_type]" ) ) {
//	      var study_list = study_info(element.attr("data-study").split(',') );
//        return '<b>'+study[iexptype]+':</b> '+study[isummary];
//          return '<b>'+study[ishortname]+':</b> '+study[idetails];
          return element.attr("data-experiment_type");
        }
        else if ( element.is( "[data-histotype_list]" ) ) {
// Convert the histotypes to their full_names:      
//        var histotype_list = element.attr("data-histotype_list").split(',');
          return histotypes_to_displaynames(element.attr("data-histotype_list"));   // was: .replace(/,/g, ', ');
        }
      }    // end of 'content:'
   });  // end of tooltip
}


    // Turn off automatic editor creation first.
    // CKEDITOR.disableAutoInline = true;
    // CKEDITOR.inline( 'editor1' );

//$(document).ready(function() {
//    add_tooltips_to_driver_table();
//    }) 
    
</script>
{% endblock %}

{% block content %}
<h1>News<h1/>
{% endblock %}
{% block table %}

<hr/>
{% comment %}
{ % for news in news_list % }
<!-- div id="editor1" contenteditable="true" -->
  {{ news.content|safe }}<p style="color:gray; font-size:80%; text-align:right;">Posted: {{ news.first_posted }}  &nbsp; Last edited: {{ news.last_edited }}</p><hr/>
{ % endfor % }
{% endcomment %}


<h2>New datasets, new drivers, new versioning approach</h2>

<p><b>November 17th 2017</b></p>

{# Optional image with Left/Right aligned, and optional url link from the image: #}

<p>We have added three new <a href="{% url 'gendep:studies' %}">datasets</a> to CancerGD.org :</p>

<ul>
	<li dir="ltr">
	<p><a href="http://www.cell.com/cell/abstract/S0092-8674(17)30651-7">Tsherniak <em>et al</em></a>, Cell 2017 - shRNA screens in 501 Cancer Cell Lines</p>
	</li>
	<li dir="ltr">
	<p><a href="http://www.cell.com/cell/fulltext/S0092-8674(17)30812-7">McDonald <em>et al</em>,</a> Cell 2017 - shRNA screens in 398 Cancer Cell Lines</p>
	</li>
	<li dir="ltr">
	<p><a href="https://www.nature.com/articles/ng.3984">Meyer <em>et al</em>,</a> Nature Genetics 2017 - CRISPR screens in 398 Cancer Cell Lines</p>
	</li>
</ul>

<p>As these datasets cover a significantly larger number of cell lines to previous screens, we have also increased the coverage of driver genes. We now store dependencies for <a href="{% url 'gendep:drivers' %}">102 driver genes</a>.</p>


<p>The dataset of <a href="http://www.cell.com/cell/abstract/S0092-8674(17)30651-7">Tsherniak <em>et al</em></a> contains a superset of the cell lines screened in <a href="https://www.nature.com/articles/sdata201435">Cowley <em>et al</em></a> and uses an improved algorithm for identifying gene specific dependencies. We previously stored dependencies identified using the <a href="https://www.nature.com/articles/sdata201435">Cowley <em>et al</em></a> dataset, but we have dropped them for this release as they have been now superseded by those from <a href="http://www.cell.com/cell/abstract/S0092-8674(17)30651-7">Tsherniak <em>et al</em></a>. We anticipate this will be a common pattern - new datasets will expand upon previously published studies, incorporating previous screens along with new screens. We will always endeavour to store the most up to date version of each dataset (e.g. <a href="http://www.cell.com/cell/abstract/S0092-8674(17)30651-7">Tsherniak <em>et al</em></a> rather than <a href="https://www.nature.com/articles/sdata201435">Cowley <em>et al</em></a>). However, for the sake of reproducibility, we will keep storing older versions of the database in both SQLite and CSV format. We have added a new <a href="{% url 'gendep:download' %}">downloads page</a> where you can download historic versions of the database. </p>


<p>We hope you find the updates useful and, as always, we welcome any <a href="{% url 'gendep:contact' %}">feedback</a>.</p>
<hr/>

{# When aligning elements with float, always define margin and padding for the 'body' element. This is to avoid visual differences in different browsers. #}

{% endblock%}

gendep/templates/gendep/targets.html
{% extends 'gendep/base.html' %}
{% load staticfiles %}
{% block content %}
<p>Details of target/dependency genes investigated:</p>
{% endblock %}
{% block table %}
<table cellpadding="3" class="tabler"> <!-- style="border: 1px solid blue;" -->
<thead><tr><th>Target gene</th><th>Entrez ID</th><th>Full name</th><th>Synonyms</th>{# <th>Num studies</th><th>Num tissues</th><th>Num drivers</th><th>External links</th> #}</tr></thead>
<tbody>
{% for target in target_list %}
<tr>
<td><a href="{% url 'gendep:home_search_by_gene' search_by='target' gene_name=target.gene_name %}">{{ target.gene_name }}</a></td>
<td>{{ target.full_name }}</td>
<td>{{ target.entrez_id }}</td>
<td><font size="-1">{{ target.prevname_synonyms }}</font></td>
{% comment %}
<td style="text-align:center">{{ target.num_studies }}</td>
<td style="text-align:center">{{ target.num_histotypes }}</td>
<td style="text-align:center">{{ target.num_driver }}</td>
<td><font size="-2">{{ target.external_links|safe }}</font></td>
{% endcomment %}
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

gendep/templates/gendep/tissues.html
{% extends 'gendep/base.html' %}
{% load staticfiles %}
{% block content %}
<p>Details of tissues investigated:</p>
{% endblock %}
{% block table %}
<table cellpadding="3" class="tabler"> <!-- style="border: 1px solid blue;" -->
<thead><tr><th>Tissue full name</th><th>Name for <a href="{% url 'gendep:faq' %}#json">JSON api</a></th><th>Studies</th><th>Comments</th></tr></thead>
<tbody>
{% for histotype in histotype_list %}
<tr>
<td>{{ histotype.1 }}</td>
<td>{{ histotype.0 }}</td>
<td></td>
<td></td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}